

//EN ESTE ARCHIVO VAN LOS ACTIONS, QUE SON SOLO CONSTANTES QUE SE LE ASIGNAN EL STRING PARA DESPUES SER COMPARADO EN EL SWITCH POR CADA ACCION


//ToDos

export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const UPDATE_TODOS = 'UPDATE_TODOS';



//Users

export const ADD_USER = 'ADD_USER';
export const UPDATE_USERS = 'UPDATE_USER';